CREATE TABLE IF NOT EXISTS USERS (
    ID SERIAL,
    USERNAME VARCHAR(255) NOT NULL,
    FULL_NAME VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    ACCOUNT_NON_EXPIRED BOOLEAN NOT NULL,
    ACCOUNT_NON_LOCKED BOOLEAN NOT NULL,
    CREDENTIALS_NON_EXPIRED BOOLEAN NOT NULL,
    ENABLED BOOLEAN NOT NULL,

    CONSTRAINT PK_USERS PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_USERS_USERNAME UNIQUE (USERNAME),
    CONSTRAINT UNIQUE_USERS_EMAIL UNIQUE (EMAIL)
);