CREATE TABLE IF NOT EXISTS USERS_ROLES (
    USER_ID INT NOT NULL,
    ROLE_ID INT NOT NULL,

    CONSTRAINT PK_USERS_ROLES PRIMARY KEY (USER_ID, ROLE_ID),
    CONSTRAINT FK_USERS_ROLES_USER FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    CONSTRAINT FK_USERS_ROLES_ROLE FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID)
);