CREATE TABLE IF NOT EXISTS ITEMS (
    ID SERIAL,
    NAME VARCHAR(255) NOT NULL,
    DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE NUMERIC(10, 2) NOT NULL,

    CONSTRAINT PK_ITEMS PRIMARY KEY (ID)
);