CREATE TABLE IF NOT EXISTS GUESTS (
    ID SERIAL,
    NAME VARCHAR(150) NOT NULL,
    EMAIL VARCHAR(150) NOT NULL,
    PHONE VARCHAR(20) NOT NULL,

    CONSTRAINT PK_GUESTS PRIMARY KEY (ID),
    CONSTRAINT UNIQUE_GUESTS_EMAIL UNIQUE (EMAIL),
    CONSTRAINT UNIQUE_GUESTS_PHONE UNIQUE (PHONE)
);